In [1]:
import numpy as np

In [2]:
S = np.arange(101)

In [5]:
A = S[[0,1,100]]
A

array([  0,   1, 100])

In [8]:
A[0]= 111
print(A)
print(S) # does not change

[111   1 100]
[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]


In [11]:
# & , and   the left side are used for arrays and the right one for single objects
# | , or
# ~ , not
A = S[(S>10) & (S<80)]
A

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44,
       45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61,
       62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78,
       79])

In [15]:
# numpy broadcasting
# numpy hstack , vstack and sort axis = 0

F = np.round(10*np.random.rand(2,3))
F

array([[7., 2., 5.],
       [9., 1., 3.]])

In [18]:
F+5 #broadcasting

array([[12.,  7., 10.],
       [14.,  6.,  8.]])

In [20]:
X = np.round(10*np.random.rand(2,2))
print(F)
print(X)

[[7. 2. 5.]
 [9. 1. 3.]]
[[ 6. 10.]
 [ 9.  3.]]


In [21]:
Y = np.hstack((F,X)) # concatenate horizontal stack
Y

array([[ 7.,  2.,  5.,  6., 10.],
       [ 9.,  1.,  3.,  9.,  3.]])

In [22]:
Z = np.random.permutation(np.arange(10))
Z

array([2, 7, 6, 4, 3, 5, 9, 8, 0, 1])

In [26]:
ZZ = np.sort(Z) 
ZZ

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
# numpy is really fast , ufuncs

C = np.random.rand(100000)
%timeit sum(C)
%timeit np.sum(C)  # same as C.sum()

2.92 ms ± 56.2 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
12.5 μs ± 65.6 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
