In [54]:
import numpy as np

In [55]:
#Numpy Dimensions

X = np.array([[1,2,3],[4,5,6]])
X.ndim

2

In [56]:
#Numpy arange

S = np.arange(10,110,10)   #for i in range(10,110,10)
print(S)

[ 10  20  30  40  50  60  70  80  90 100]


In [57]:
#Numpy random

A = np.random.permutation(np.arange(11))
print(A)
B = np.random.randint(10,100)
print(B)

[ 9  6  1  4  0 10  8  7  3  5  2]
82


In [58]:
#Numpy Slicing     A[Start:End:Step]

C = np.arange(50)
D = C[20:50]
print(D)

[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [59]:
C[0] = 100
print(C)
print(D)

[100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49]
[20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43
 44 45 46 47 48 49]


In [60]:
print(C[::2])
print(C[::-2])

[100   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48]
[49 47 45 43 41 39 37 35 33 31 29 27 25 23 21 19 17 15 13 11  9  7  5  3
  1]


In [61]:
idx = np.argwhere(C==100)[0][0]
print(idx)

0


In [62]:
Y = np.round(10*np.random.rand(3,3))
print(Y)

[[9. 2. 9.]
 [4. 0. 8.]
 [6. 3. 5.]]


In [63]:
print(Y[0,1]) 
print(Y[1,:]) # access second row
print(Y[:,1]) # access second column

2.0
[4. 0. 8.]
[2. 0. 3.]


In [64]:
Y.sort(axis=0) #sort all column
Y

array([[4., 0., 5.],
       [6., 2., 8.],
       [9., 3., 9.]])

In [65]:
Y.sort(axis=1) #sort all row
Y

array([[0., 4., 5.],
       [2., 6., 8.],
       [3., 9., 9.]])